// Generated by impulse-graph-spec codegen tool (v2.4.0).
#ifndef IMPULSE_GRAPH_FORMAT_V2_4_H
#define IMPULSE_GRAPH_FORMAT_V2_4_H

#include "impulse_graph.h"

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#define IMPULSE_SPEC_VERSION_MAJOR_V2_4 2
#define IMPULSE_SPEC_VERSION_MINOR_V2_4 4
#define IMPULSE_SPEC_MAGIC_V2_4 0x494D5053
#define IMPULSE_SPEC_HEADER_BASELINE_OFFSET_V2_4 4096

#pragma pack(push, 1)

// Section 2 Part A: Fixed 64-byte Domain Catalog Entry (v2.4)
typedef struct impulse_domain_catalog_entry_v2_4_t {
    uint16_t domain_id;          // 0x00..0x01
    uint8_t key_type;            // 0x02
    uint8_t reserved1;           // 0x03
    uint64_t node_count;         // 0x04..0x0B
    uint64_t required_features;  // 0x0C..0x13
    uint64_t compat_features;    // 0x14..0x1B
    uint64_t aux_sections_pos;   // 0x1C..0x23
    uint64_t aux_sections_size;  // 0x24..0x2B
    uint32_t name_offset;        // 0x2C..0x2F
    uint16_t name_length;        // 0x30..0x31
    uint8_t reserved2[14];       // 0x32..0x3F (Pads to 64 bytes)
} impulse_domain_catalog_entry_v2_4_t;

#ifdef __cplusplus
static_assert(sizeof(impulse_domain_catalog_entry_v2_4_t) == 64,
              "impulse_domain_catalog_entry_v2_4_t size mismatch with spec v2.4.0");
#endif

// Section 2 Part B: Fixed 128-byte Relation Directory Metadata Entry (v2.4)
typedef struct impulse_relation_directory_entry_v2_4_t {
    uint16_t src_domain_id;       // 0x00..0x01
    uint16_t tgt_domain_id;       // 0x02..0x03
    uint8_t encoding_type;        // 0x04
    uint64_t node_count;          // 0x05..0x0C
    uint64_t edge_count;          // 0x0D..0x14
    uint64_t required_features;   // 0x15..0x1C
    uint64_t compat_features;     // 0x1D..0x24
    uint64_t csr_offsets_pos;     // 0x25..0x2C
    uint64_t csr_offsets_size;    // 0x2D..0x34
    uint64_t csr_targets_pos;     // 0x35..0x3C
    uint64_t csr_targets_size;    // 0x3D..0x44
    uint64_t aux_sections_pos;    // 0x45..0x4C
    uint64_t aux_sections_size;   // 0x4D..0x54
    uint32_t name_offset;         // 0x55..0x58
    uint16_t name_length;         // 0x59..0x5A
    uint16_t tgt_node_count_lo16; // 0x5B..0x5C
    uint8_t reserved[35];         // 0x5D..0x7F (Pads to 128 bytes)
} impulse_relation_directory_entry_v2_4_t;

#ifdef __cplusplus
static_assert(sizeof(impulse_relation_directory_entry_v2_4_t) == 128,
              "impulse_relation_directory_entry_v2_4_t size mismatch with spec v2.4.0");
#endif

#pragma pack(pop)

#ifdef __cplusplus
}
#endif

#endif // IMPULSE_GRAPH_FORMAT_V2_4_H