// Generated by impulse-graph-spec codegen tool (v2.3.0). DO NOT EDIT MANUALLY.
#ifndef IMPULSE_GRAPH_FORMAT_V2_3_H
#define IMPULSE_GRAPH_FORMAT_V2_3_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#define IMPULSE_SPEC_VERSION_MAJOR_V2_3 2
#define IMPULSE_SPEC_VERSION_MINOR_V2_3 3
#define IMPULSE_SPEC_MAGIC_V2_3 0x494D5053
#define IMPULSE_SPEC_HEADER_BASELINE_OFFSET_V2_3 4096

#define IMPULSE_GLOBAL_FEAT_4KB_PAGE_ALIGNED 0x0000000000000008ULL

#define IMPULSE_SECTION_FEAT_RAW_UINT32 0x0000000000000001ULL
#define IMPULSE_SECTION_FEAT_DELTA_VBYTE 0x0000000000000002ULL
#define IMPULSE_SECTION_FEAT_RAW_UINT16 0x0000000000000004ULL
#define IMPULSE_SECTION_FEAT_SIMDCOMP 0x0000000000000010ULL

// C-ABI Status and Error Return Codes (v2.3)
typedef enum impulse_status_t {
    IMPULSE_OK = 0,
    IMPULSE_ERR_INVALID_MAGIC = 1,
    IMPULSE_ERR_UNSUPPORTED_VERSION = 2,
    IMPULSE_ERR_UNSUPPORTED_GLOBAL_FEATURE = 3,
    IMPULSE_ERR_UNSUPPORTED_SECTION_FEATURE = 4,
    IMPULSE_ERR_CORRUPT_CHECKSUM = 5,
    IMPULSE_ERR_IO_FAILURE = 6,
    IMPULSE_ERR_INVALID_ARGUMENT = 7
} impulse_status_t;

// Domain Catalog Key Type Enums
typedef enum impulse_key_type_t {
    IMPULSE_KEY_TYPE_INT16 = 0,
    IMPULSE_KEY_TYPE_INT32 = 1,
    IMPULSE_KEY_TYPE_INT64 = 2,
    IMPULSE_KEY_TYPE_UUID = 3,
    IMPULSE_KEY_TYPE_STRING = 4
} impulse_key_type_t;

// Primary Topology CSR Encoding Enums (v2.3)
typedef enum impulse_encoding_type_t {
    IMPULSE_ENC_RAW_UINT32 = 0,
    IMPULSE_ENC_DELTA_VBYTE = 1,
    IMPULSE_ENC_RAW_UINT16 = 2,
    IMPULSE_ENC_HYBRID_16_32 = 3,
    IMPULSE_ENC_SIMDCOMP = 4,
    IMPULSE_ENC_SLICED_ELLPACK = 5,
    IMPULSE_ENC_TPU_BCOO = 6
} impulse_encoding_type_t;

#pragma pack(push, 1)

// Section 1 Fixed 4KB Baseline Snapshot Header (v2.3)
typedef struct impulse_snapshot_header_v2_3_t {
    uint32_t magic; // Magic constant (0x494D5053 = 'IMPS')
    uint16_t version; // Protocol major version number
    uint32_t data_offset; // Byte offset where Section 2 payload begins
    uint16_t domain_count; // Total number of domains in domain catalog
    uint16_t relation_count; // Total number of relations in matrix
    uint64_t kafka_offset; // Kafka Write-Ahead Log (WAL) offset
    uint64_t timestamp_ms; // Unix epoch timestamp (milliseconds)
    uint8_t sha256[32]; // Cryptographic SHA-256 checksum
    uint8_t reserved[2]; // Reserved baseline alignment padding
    uint64_t global_required_features; // Global Feature-in-Use Bitmask
} impulse_snapshot_header_v2_3_t;

static_assert(sizeof(impulse_snapshot_header_v2_3_t) == 1096,
              "impulse_snapshot_header_v2_3_t size mismatch with spec v2.3.0");

// Section 2 Relation Directory Metadata Entry (v2.3)
typedef struct impulse_relation_directory_entry_v2_3_t {
    uint16_t src_domain_id; // Domain ID of source nodes
    uint16_t tgt_domain_id; // Domain ID of target nodes
    uint8_t encoding_type; // Primary CSR matrix compression encoding flag
    uint64_t node_count; // Total number of source nodes (N)
    uint64_t edge_count; // Total number of directed edges (E)
    uint64_t section_features; // Per-Section Feature-in-Use Bitmask
    uint64_t csr_row_off_offset; // Absolute File Offset to RowOffsets array
    uint64_t csr_row_off_bytes; // Byte size of RowOffsets array
    uint64_t csr_col_idx_offset; // Absolute File Offset to ColumnIndices array
    uint64_t csr_col_idx_bytes; // Byte size of ColumnIndices stream
    uint64_t id_map_offset; // Absolute File Offset to Section 4 (ID Mappings)
    uint64_t id_map_bytes; // Byte size of Section 4 (ID Mappings)
    uint64_t dto_lookup_offset; // Absolute File Offset to Section 5 (DTO Lookup Payload)
    uint64_t dto_lookup_bytes; // Byte size of Section 5 (DTO Lookup Payload)
    uint64_t delta_log_offset; // Absolute File Offset to Section 6 (Delta Log)
    uint64_t delta_log_bytes; // Byte size of Section 6 (Delta Log)
} impulse_relation_directory_entry_v2_3_t;

static_assert(sizeof(impulse_relation_directory_entry_v2_3_t) == 109,
              "impulse_relation_directory_entry_v2_3_t size mismatch with spec v2.3.0");

#pragma pack(pop)

#ifdef __cplusplus
}
#endif

#endif // IMPULSE_GRAPH_FORMAT_V2_3_H